const data = {
    terms: [
        { word: "Adaptability", def: "The ability to play offense or defense, depending on what the situation calls for." },
        { word: "Advantage", def: "Having more of a resource than your opponent, or any other beneficial position relative to your opponent." },
        { word: "Aggro", def: "Short for 'aggressive', aggro is used to define a deck or archetype which is highly dependent on creature combat and aggressive attacks (also 'beatdown'). The aim is to develop an advantage in the game before the opponent. Usually, aggro decks have a low mana curve and try to overwhelm the opponent before they can build any board presence or stabilize." },
        { word: "Alpha-Strike", def: "A final all-out attack for a lethal amount of damage, intended to win the game that turn." },
        { word: "Archetype", def: "Any recurring strategy with numerous possible variations" },
        { word: "Aristocrat", def: "A creature with an activated ability involving sacrificing another creature. E.g. Teysa, Orzhov Scion; OR deck archetype (Aristocrats) that aims to benefit from sacrificing its own cards." },
        { word: "Bant", def: "USed to describe any Blue/White/Green card or deck." },
        { word: "Bear", def: "A 2/2 creature with no abilities that costs 2 Mana (i.e. Grizzly Bear)" },
        { word: "Blank", def: "'To blank a card.' To turn one of your opponent's cards into a dead card." },
        { word: "Board Stall", def: " The situation where the battlefield is clogged with creatures, and neither player can profitably attack. (Also called 'Creature Stall.')" },
        { word: "Board Sweeper", def: "Cards capable of destroying many creatures at once. (Also called 'Wraths.')" },
        { word: "Bomb", def: "A card so powerful that it will often determine the game all on its own. (Term used more commonly with regard to Limited than Constructed.)" },
        { word: "Bottleneck", def: "A limiting factor. To be 'bottlenecked on mana' is to have more things to do with your mana than you have mana available." },
        { word: "Bounce", def: "To return a card to its owner's hand." },
        { word: "Burn", def: "Spells that can deal damage to creatures and/or players. Burn is a hallmark of the color red, and is an example of reach. (Also called 'Direct Damage.')" },
        { word: "Card Advantage", def: "Any process by which a player effectively obtains more cards than his or her opponent." },
        { word: "Card Quality", def: "The ability of your cards to influence the outcome of the game." },
        { word: "Card Quantity", def: "The gross number of cards that you have access to." },
        { word: "Chump Block", def: "To block with a creature in order to preserve your life total, even though yours will be the only creature dying in the exchange." },
        { word: "Combat Trick", def: "An instant-speed spell that can improve or save your creature (or otherwise affect the board state in your favor) during combat" },
        { word: "Consistency", def: "Resilience against things going wrong. A deck is consistent if its failure rate is low and it can operate on a reasonable level in a relatively high portion of game" },
        { word: "Constructed", def: "For Constructed events, you bring a deck of at least 60 cards from home. Examples: Standard, Modern, Legacy." },
        { word: "Control", def: "A control deck focuses on shutting down the opponent, and only wins the game later, at its own convenience." },
        { word: "Counterdraft", def: "Spend a pick taking a card out of the draft, so no one else can have it." },
        { word: "Creature Land", def: "A land with the ability to become a creature" },
        { word: "Critical Mass", def: "Some strategies grow rapidly in power as more cards that contribute to the strategy are added. For such strategies, critical mass is the tipping point where the strategy can be successfully put into effect." },
        { word: "Deathtouch", def: "A creature dealt any amount of damage by a creature with deathtouch is destroyed. Deathtouch has no effect on players or planeswalkers." },
        { word: "Exile", def: "Some spells and abilities can exile permanents on the battlefield or cards in other zones. Exiled cards are set apart from the rest of the game. You can’t interact with cards in exile unless an ability specifies otherwise." },
        { word: "Flying", def: "A creature with flying can be blocked only by creatures with flying or reach." },
        { word: "Haste", def: "A creature with haste isn’t affected by summoning sickness. It can attack as soon as it comes under your control." },
        { word: "Lifelink", def: "When a creature you control has lifelink and deals damage, you simultaneously gain that much life." },
        { word: "Reach", def: "A creature with reach can block a creature with flying. Note that a creature with reach can be blocked by any kind of creature." },
        { word: "Scry", def: "Scry is a keyword action that allows a player to look at a certain number of cards from the top of their library and put them on the bottom of the library or back on top in any order." },
        { word: "Surveil", def: "Surveil is a keyword action that allows a player to look at a certain number of cards from the top of their library and put them in the graveyard or back on top in any order." },
        { word: "Shuffle", def: "Some cards will instruct you to shuffle. This is a keyword action that has you randomize the cards of your library, so that no one knows the order of its contents." },
        { word: "Source", def: "Damage and abilities each come from a spell or permanent—the source of that damage or ability. Once an ability is on the stack, removing its source doesn’t stop it from resolving." },
        { word: "Spell", def: "All types of cards (except lands) are spells while you’re casting them. For example, Angler Turtle is a creature card. While you’re casting it, it’s a creature spell. When it resolves, it becomes a creature. Spells can only be cast during your main phase, except for instants, which can be cast anytime." },
        { word: "Token", def: "Some spells and abilities can create tokens. Tokens are always permanents, and they’re affected by all the rules, spells, and abilities that affect permanents. If one of your tokens leaves the battlefield, however, it moves to the new zone (such as your graveyard or your hand) and then immediately vanishes from the game." },
        { word: "Trample", def: " Trample allows a creature to deal excess combat damage to the player it’s attacking, even if the creature is blocked. If you’re attacking with a creature that has trample and it is blocked, you have to assign its combat damage to the creatures blocking it first. If it destroys all of those creatures, then you can assign any excess damage to the player it’s attacking. If an attacking creature with trample is blocked, but there are no creatures blocking it when damage is assigned (for example, if you used a spell to destroy the blocking creature), then all of its damage is assigned to the player it’s attacking. Trample does not work on Planeswalkers, unless the creature has “Trample over planeswalkers”." },
    ]
}
    // { word: "", def: "" },